#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx

- name: install nginx package от RedHat
  yum:
    name: nginx
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: install nginx package on debian systems
  apt:
    name: nginx
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: ensure nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: true
  become: yes

- name: disable default site if required
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  when: not nginx_default_sites_enabled

- name: deploy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: yes
  notify:
    - reload nginx