---
# tasks file for docker
- block:
    - name: add GPG key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repository for docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{
          ansible_distribution_release }} stable
        state: present

    - name: update cashe
      apt:
        update_cache: yes

    - name: install docker
      apt:
        name: "{{ item }}" #option №1 to install of docker-compose
        state: present
#        update_cache: yes
      loop:
        - "{{ app_list }}"

    - name: check/start docker service
      service:
        name: docker
        state: started
        enabled: yes
  become: yes

- name: Adding user to docker group  
  user: 
    name: "{{ remote_user }}"
    groups: docker
    append: yes
  become: yes

- name: Install Docker-Compose and Set Permissions #option №2 to install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ dock_comp_vers }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'
  become: yes

# S1e9 создаем докерфайл с nginx и lua, тестируем  
- name: copy file for task
  copy:
    src: files/
    dest: /docker
    owner: user
    group: user
    mode: '0644'
  become: yes

# гуглить ansible docker build и править задачу
- name: create dockerfile
  shell: cd /docker && docker build -t lua .

#  далее подключаемся к виртуалке, запускаем контейнер:
#  docker run -d -p 81:81 --name lua lua
#  и если все ок, то выгружаем страничку:
#  wget http://localhost:81
#  должен выгрузиться файл index.html с текстом Hello Word
#  cat index.html
    