---
# tasks file for common
- name: set timezone to {{ TZ }}
  timezone:
    name: "{{ TZ }}"
  become: yes

- block:
    - name: create a swap file
      shell: fallocate -l {{ swap_size }} /{{ swap_file }}
      args:
        creates: "{{ swap_file }}"

    - name: set the correct permissions
      file:
        path: "{{ swap_file }}"
        owner: root
        group: root
        mode: '0600'

    - name: make the file a swap file
      shell: mkswap {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swap_file }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
  become: yes

# tasks for changing hostnames
- name: changing hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
#    name: "{{ hostname }}"
  become: yes

# tasks for installation packages
- name: installation packages
  apt:
    name:  "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ packages }}"
  become: yes

# task for installtion special applications

- name: installation packages
  apt:
    name:  "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ packages }}"
  become: yes

# #s1e15 task 1
- name: check load average
  shell: uptime | awk '{print $9, $10, $11, $12, $13}' #or uptime | cut -d' ' -f10-15
  register: load_avg
  
- debug: 
    msg: "{{ load_avg }}"
- name: load average short form
  debug: 
    var: load_avg.stdout #более короткий вариант