---
 #tasks file for swaptrasher, #s1e15 task 2
- name: find swapfile
  shell: echo $(awk '{print $1}' /proc/swaps | tail -1) #searh where is swap file in system and put answer in var $swap_path
  register: swap_path

- name: print swap path
  debug:
    var: swap_path.stdout

# #s1e15 task 1
- name: check load average
  shell: uptime | awk '{print $9, $10, $11, $12, $13}'
  register: load_avg
  
- debug: 
    msg: "{{ load_avg }}"
- name: load average short form
  debug: 
    var: load_avg.stdout #более короткий вариант

- block:
  - name: turn off a swap
    shell: swapoff -a
    become: yes

  - name: delete a swap file
    file: 
      path: "{{ swap_path }}" 
      state: absent
#    when: ansible_facts.swapfree_mb > 0
    become: yes

  - name: delete swap file from fstab
    mount:
      name: none
      src: "{{ swap_path }}"
      fstype: swap
      opts: sw
      passno: 0
      dump: 0
      state: absent_from_fstab
    become: yes